2023-07-19 22:14:31,943 (63213/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-19 22:14:31,943 (63213/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-19 22:14:38,067 (63213/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 636, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n'
2023-07-19 22:14:45,654 (64094/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-19 22:14:45,654 (64094/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-19 22:14:49,838 (64094/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 636, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n'
2023-07-19 22:15:16,009 (64928/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-19 22:15:16,010 (64928/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-19 22:15:18,850 (64928/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 630, in connect\n    passwd = click.prompt(\n             ^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/click/termui.py", line 166, in prompt\n    value = prompt_func(prompt)\n            ^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/click/termui.py", line 149, in prompt_func\n    raise Abort() from None\nclick.exceptions.Abort\n'
2023-07-19 22:20:00,932 (72473/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-19 22:20:00,932 (72473/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-19 22:20:00,965 (72473/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n'
2023-07-19 22:20:05,887 (73387/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-19 22:20:05,887 (73387/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-19 22:20:08,340 (73387/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 636, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n'
2023-07-19 22:20:28,022 (74329/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-19 22:20:28,022 (74329/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-19 22:20:31,046 (74329/MainThread) pgcli.pgexecute ERROR - sql: 'ls', error: SyntaxError('syntax error at or near "ls"\nLINE 1: ls\n        ^')
2023-07-19 22:20:31,047 (74329/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "ls"\nLINE 1: ls\n        ^\n'
2023-07-20 02:13:59,489 (74611/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-20 02:13:59,490 (74611/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-20 02:14:01,588 (74611/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 636, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n'
2023-07-20 02:14:17,803 (76144/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-20 02:14:17,803 (76144/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-20 02:14:44,567 (76144/MainThread) pgcli.pgexecute ERROR - sql: 'drop database dev', error: ObjectInUse('cannot drop the currently open database')
2023-07-20 02:14:44,569 (76144/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.ObjectInUse: cannot drop the currently open database\n'
2023-07-22 18:40:10,892 (85557/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-22 18:40:10,893 (85557/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-22 18:40:13,063 (85557/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 636, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n'
2023-07-22 18:40:16,148 (86260/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-22 18:40:16,148 (86260/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-22 18:40:16,546 (86260/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 636, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n'
2023-07-22 18:40:18,516 (86950/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-22 18:40:18,516 (86950/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-22 18:44:20,724 (86950/MainThread) pgcli.pgexecute ERROR - sql: 'delete database dev', error: SyntaxError('syntax error at or near "database"\nLINE 1: delete database dev\n               ^')
2023-07-22 18:44:20,728 (86950/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "database"\nLINE 1: delete database dev\n               ^\n'
2023-07-22 18:44:27,797 (86950/MainThread) pgcli.pgexecute ERROR - sql: 'delete database dev', error: SyntaxError('syntax error at or near "database"\nLINE 1: delete database dev\n               ^')
2023-07-22 18:44:27,798 (86950/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "database"\nLINE 1: delete database dev\n               ^\n'
2023-07-22 18:44:36,862 (86950/MainThread) pgcli.pgexecute ERROR - sql: 'delete dev', error: SyntaxError('syntax error at or near "dev"\nLINE 1: delete dev\n               ^')
2023-07-22 18:44:36,863 (86950/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "dev"\nLINE 1: delete dev\n               ^\n'
2023-07-22 18:44:51,611 (86950/MainThread) pgcli.pgexecute ERROR - sql: 'drop database dev', error: ObjectInUse('database "dev" is being accessed by other users\nDETAIL:  There is 1 other session using the database.')
2023-07-22 18:44:51,612 (86950/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.ObjectInUse: database "dev" is being accessed by other users\nDETAIL:  There is 1 other session using the database.\n'
2023-07-23 17:04:27,092 (11368/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-23 17:04:27,092 (11368/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-23 17:06:58,571 (12988/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-23 17:06:58,571 (12988/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-25 18:53:08,818 (4509/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-25 18:53:08,819 (4509/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-25 18:54:00,568 (4509/MainThread) pgcli.pgexecute ERROR - sql: '\\t', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\t\n        ^')
2023-07-25 18:54:00,572 (4509/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\t\n        ^\n'
2023-07-25 18:54:02,283 (4509/MainThread) pgcli.pgexecute ERROR - sql: '\\s', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\s\n        ^')
2023-07-25 18:54:02,284 (4509/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\s\n        ^\n'
2023-07-25 18:58:20,552 (11389/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-25 18:58:20,552 (11389/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-25 18:58:40,045 (11389/MainThread) pgcli.pgexecute ERROR - sql: 'q', error: SyntaxError('syntax error at or near "q"\nLINE 1: q\n        ^')
2023-07-25 18:58:40,048 (11389/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "q"\nLINE 1: q\n        ^\n'
2023-07-25 19:04:35,904 (16920/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-25 19:04:35,904 (16920/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-25 19:04:48,947 (16920/MainThread) pgcli.pgexecute ERROR - sql: '\\t', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\t\n        ^')
2023-07-25 19:04:48,951 (16920/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\t\n        ^\n'
2023-07-26 02:45:20,297 (89136/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-26 02:45:20,297 (89136/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-26 02:48:48,620 (96809/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-26 02:48:48,620 (96809/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-26 02:48:50,332 (96809/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 636, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n'
2023-07-26 02:48:52,863 (97696/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-26 02:48:52,863 (97696/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-26 02:51:02,313 (6115/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-26 02:51:02,313 (6115/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-26 19:13:08,953 (28308/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-26 19:13:08,953 (28308/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-26 19:44:19,283 (43265/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-26 19:44:19,283 (43265/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-26 19:44:20,917 (43265/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 636, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 728, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n'
2023-07-26 19:44:23,108 (44076/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-26 19:44:23,108 (44076/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-26 19:44:31,367 (44076/MainThread) pgcli.pgexecute ERROR - sql: 'drop database dev', error: InvalidCatalogName('database "dev" does not exist')
2023-07-26 19:44:31,370 (44076/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.InvalidCatalogName: database "dev" does not exist\n'
2023-07-26 19:45:44,395 (48339/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-26 19:45:44,395 (48339/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
